<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/slick/slick.css', 'ItemCarouselBlock'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/slick/slick-theme.css', 'ItemCarouselBlock'));
$this->headLink()->appendStylesheet($this->assetUrl('css/item-carousel.css', 'ItemCarouselBlock'));
$this->headScript()->appendFile($this->assetUrl('vendor/slick/slick.min.js', 'ItemCarouselBlock'));
?>
<div class="carousel-block">
	<?php if ($this->carouselHeading): ?>
	<h2><?php echo $this->carouselHeading; ?></h2>
	<?php endif; ?>
	<div class="carousel">
	<?php
		foreach ($attachments as $attachment) {
			$item = $attachment->item();
			$media = $attachment->media() ?: $item->primaryMedia();
			$caption = $this->showCaption == 'true' ? $attachment->caption() : '';
			$title = '';
						
			if ($this->showTitleOption == 'item_title') {
				$title = $item->displayTitle();
			} elseif ($this->showTitleOption == 'file_name') {			
				$title = $media ? $media->displayTitle() : $item->displayTitle();
			}
			
			if ($this->showTitleOption == 'no_title' && $this->showCaption == 'false') {
				$textDiv = '';
			} elseif ($this->showTitleOption == 'no_title' && $this->showCaption == 'true') {			
				$textDiv = sprintf('<div class="slide-text"><div class="caption">%s</div></div>', $caption);
			} elseif ($this->showTitleOption != 'no_title' && $this->showCaption == 'false') {			
				$textDiv = sprintf('<div class="slide-text"><div class="title">%s</div></div>', $title);
			} else {
				$textDiv = sprintf('<div class="slide-text"><div class="title">%s</div><div class="caption">%s</div></div>', 
				$title, $caption);
			}
			
			if ($media) {
				$slide = $this->thumbnail($media, $this->thumbnailType) . $textDiv;
				echo $item->linkRaw($slide);
			} else {
				$slide = $textDiv;
				echo $item->linkRaw($slide);
			} 
		}
	?>
	</div>

	<script>
	$(document).ready(function() {
		$('.carousel')
			.slick({
				slidesToShow: <?php echo $this->perPage ?>,
				slidesToScroll: 1,
				infinite: <?php echo $this->loop ?>,
				draggable: true,
				<?php if ($this->fade): ?>
				fade: <?php echo $this->fade ?>,
				<?php endif; ?>
				<?php if ($this->autoSlideDuration > 0): ?>
				autoplay: true,
				autoplaySpeed: <?php echo $this->autoSlideDuration ?>,
				<?php endif; ?>
				pauseOnHover: true,
				centerMode: false,
				arrows: true,
				dots: true,
				adaptiveHeight: true,
			});
		$('.slick-slide').css({
				'text-align': '<?php echo $this->slideCSSTextAlign ?>',
			});
		<?php if ($this->perPage > 1): ?>
			$('.slick-track').css({
				'align-items': 'center',
			});
		<?php endif; ?>
		<?php if ($this->slideCSSStretch == 'width'): ?>
			$('.slick-slide > img').css({
				'width': '100%',
				'object-fit': 'cover',
			});
			$('.slick-track').css({
				'align-items': 'initial',
			});
		<?php endif; ?>
		<?php if ($this->slideCSSStretch == 'height'): ?>
			$('.slick-slide > img').css({
				'height': '100%',
				'object-fit': 'cover',
			});
			$('.slick-track').css({
				'align-items': 'initial',
			});
		<?php endif; ?>
		<?php if ($this->slideCSSStretch == 'entire'): ?>
			$('.slick-slide > img').css({
				'width': '100%',
				'height': '100%',
				'object-fit': 'cover',
			});
			$('.slick-track').css({
				'align-items': 'initial',
			});
		<?php endif; ?>
		<?php if ($this->floatCaption == 'true'): ?>
			$('.slick-slide > div').css({
				'position': 'absolute',
				'margin': '',
			});			
			$('.slick-slide > img').css({
				'margin': '',
			});
			$('.slick-track .slick-slide').css({
				'display': 'flex',
			});
		<?php endif; ?>
		<?php if ($this->thumbnailType != 'large'): ?>
			$('.slick-track .slick-slide').css({
				'align-items': 'center',
			});
		<?php endif; ?>
	});
	</script>
</div>
